language: node_js
node_js: node
cache:
  directories:
  - node_modules
install:
- npm install
script: true
env:
- CI=true
deploy:
  provider: heroku
  api_key:
    secure: i5lgTupQX5zG9uYNElMBsM86KTTcKQI2nsu+yiiKgEyZLhc79n56/gXxn6HGwEDAvlsCZBQb1JhJdLkEZULc+MoNPI5frMBoOfMD83pLoR6+xUVvqzK1+Zh6u98nvzA3ZWEGDfagcPsNzKs7jlEA3FlXIwR6RIHStTmThxYsbCH4lSGQUGw7eFczDaLRIy9YXnGBQFX5MX+shJ/bmKviN6rGpg2/MaPE4nhvldUk4CZ1DlWtp/CZG0AfkoBSmz75wGsOUU9VNlY5OGvjQT+viJTBgisf/SInpYh5schcOksV/hS3cAxayYXOS8yKIpc2Wu+O/hMkG1BHkICOK15Ta0okTrAJ2poDpk509arwIOMYCM67LhkdRVFYLk+sJALA8r98AW0jyrO5WQhHOs+4YAjtLvNlYA0ThVhQB7Q2+V1SltBIe+vlLVutxavDgaXzAPf2llQ3ZJV4Cx3eD0qxqsCIo+TKVCE8duKhy5cVRg81C+HRmmPu3/XRcGWdlYuPmCVmme6KA49Mz0Ve8VYjWWeVTNwmK42388yItEA175MRXg44bToxJPAnpwoJREgxbCL2NZ6jHU0vnQSdHt7iDyqTd1opYt3R9KMh2HCtMW8nrBvrQOnIDA5drn+F71blp2arx2TWo1E+ksDFW59qgpRdIDEHTT+IM5xBqLAANaQ=
  app: jmaxwell-bookmark-manager
  on:
    repo: maxjeffwell/bookmarks-react-hooks
