language: node_js
node_js: node
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm test
env:
  - CI=true
deploy:
  provider: heroku
  api_key:
    secure: 9c0a3e37-422f-44a0-a122-28cc3a6eee35
  app: jmaxwell-bookmark-manager
  on:
    repo: maxjeffwell/bookmarks-react-hooks